# Build settings
[build]
  publish = "dist"
  command = "npm install && npm run build"

# Redirects
[[redirects]]
  from = "/"
  to = "/blog/"
  status = 301
  force = true

# Redirect for _astro assets
[[redirects]]
  from = "/blog/_astro/*"
  to = "/_astro/:splat"
  status = 200

# Redirect for favicon
[[redirects]]
  from = "/blog/favicon.svg"
  to = "/favicon.svg"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

# Headers for better performance
[[headers]]
  for = "/blog/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/blog/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 