backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/blog/images"

collections:
  - name: "blog"
    label: "Juicy Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "excerpt", label: "Excerpt", widget: "text", hint: "Brief description for SEO and previews" }
      - { name: "publishDate", label: "Publish Date", widget: "datetime" }
      - { name: "updatedDate", label: "Updated Date", widget: "datetime", required: false }
      - { name: "isFeatured", label: "Featured Post", widget: "boolean", default: false }
      - name: "tags"
        label: "Tags"
        widget: "list"
        default: ["DeFi", "Solana", "LP"]
        hint: "Add relevant tags like: DeFi, Solana, LP, Trading, Tutorial, Strategy"
      - name: "seo"
        label: "SEO Settings"
        widget: "object"
        collapsed: true
        fields:
          - name: "image"
            label: "SEO Image"
            widget: "object"
            fields:
              - { name: "src", label: "Image Path", widget: "image" }
              - { name: "alt", label: "Alt Text", widget: "string" }
      - { name: "body", label: "Content", widget: "markdown" }

  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "src/data/site-config.ts"
        fields:
          - { name: "title", label: "Site Title", widget: "string" }
          - { name: "subtitle", label: "Site Subtitle", widget: "string" }
          - { name: "description", label: "Site Description", widget: "text" } 